version: "3"

services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env

  app:
    build:
      context: .
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
